In [5]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [6]:
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
  print(f"{i}D Array:{arr}\nShape: {arr.shape}\n")

0D Array:5
Shape: ()

1D Array:[1 2 3 4 5]
Shape: (5,)

2D Array:[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [7]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [8]:

import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [9]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [10]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2.11306936e-319 0.00000000e+000 2.41907520e-312]
 [2.46151512e-312 5.16836490e+241 7.41098469e-323]]


In [13]:
import numpy as np
array = np.array([1, 2, 3])
# Multiplies each element by 2, result: [2, 4, 6]
print(array)
new_array = array * 2
print(new_array)
# Creates a new array with the same elements
copied_array = np.copy(array)
print(copied_array)
# Slices elements from index 1 to 3, result:[2]
sliced_array = array[1:2]
print(sliced_array)

[1 2 3]
[2 4 6]
[1 2 3]
[2]


In [14]:

import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Concatenate along axis 0 (vertical) Shape: (4, 2)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Concatenate along axis 1 (horizontal) Shape: (2, 4)
print(concat_axis0, concat_axis1, sep='\n')

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [15]:
import numpy as np
# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])
# Slicing examples
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])
# Output Basic: arr1d:[1 2 3] arr2d:[[3 4] [6 7]] arr3d:[[[5] [7]]]
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])
# Output: Step: [1 3] [[1] [7]] [[[1] [9]]]

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


In [16]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2)) # Output Add: [5 7 9]
print("Subtract:", np.subtract(arr1, arr2))
# Output Subtract: [-3 -3 -3]
print("Divide:", np.divide(arr1, arr2))
# Output Divide: [0.25 0.4 0.5 ]
print("Multiply:", np.multiply(arr1, arr2))
# Output Multiply: [ 4 10 18]
print("Power:", np.power(arr1, arr2))
# Output Power: [ 1 32 729]
print("Exp:", np.exp(arr1))
# Output Exp: [ 2.71828183 7.3890561 20.08553692]

Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


In [17]:
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape: (2, 2)

Result with np.dot:
 [[ 58  64]
 [139 154]]


In [18]:

import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print("Result with @ operator:\n", result_at) # Output shape: (2, 2)
# Matrix multiplication using np.matmul
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul) # Output shape: (2, 2)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


In [19]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5 -0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant: -2.0
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Outptut: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A, B))
#Output: Solution x: [-4. 4.5]

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


In [20]:

import numpy as np

a=np.empty((2,2))
print(a)
b=np.ones((4,2))
print(b)
c=np.full((2,2),4)
print(c)
d=np.zeros_like(c)
print(d)
e=np.ones_like(c)
print(e)
new_list = [1,2,3,4]
f=np.array(new_list)
print(f)

[[1. 2.]
 [3. 4.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[4 4]
 [4 4]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [21]:
g=np.arange(10,50)
print(g)
h=np.random.random(30)
print(h)
i=h.mean()
print(i)
j=np.random.random((10,10))
print(j)
k=j.max()
l=j.min()
print("Maximum Vlaue ",k,"minimum value ",l)
m=np.zeros(10)
m[4]=1
print(m)
n=np.array([1,2,0,0,4,0])
print(n)
rev = n[::-1]
print(rev)
o=np.ones((5,5))
o[1:-1,1:-1]=0
print(o)
p=np.random.randint(0,10,(8,8))
p[::2,::2]=1
p[1::2,1::2]=1
p[::2, 1::2]=0
p[1::2,::2]=0
print(p)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[0.49568192 0.75972381 0.88386447 0.21254717 0.52058202 0.33941722
 0.09092125 0.80015197 0.61912799 0.80273644 0.84990447 0.19190079
 0.30021721 0.91705028 0.53496378 0.91065028 0.1996504  0.11858421
 0.32395266 0.57985951 0.0695236  0.31609641 0.47928417 0.46211732
 0.80545623 0.18169533 0.00902765 0.11912255 0.06980553 0.69150327]
0.4551706650200497
[[6.68740859e-02 4.55189517e-01 4.18161082e-01 3.17298555e-01
  4.31363219e-01 7.33466959e-01 2.05868812e-05 1.58145236e-01
  2.89094435e-01 5.72779159e-01]
 [3.15672260e-01 3.20974082e-01 1.37516254e-01 2.67590593e-01
  8.48392013e-01 7.82392507e-01 8.38329069e-01 7.01299308e-01
  1.06757693e-03 5.17580719e-02]
 [6.76772965e-01 8.61556711e-01 8.34477885e-03 1.79896530e-01
  5.60013248e-01 8.50204484e-01 6.47897928e-01 7.22947619e-01
  1.93748546e-01 5.40349818e-01]
 [5.37980169e-01 5.72710964e-01 6.59306623e-01 2.73

In [22]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
AInverse = np.linalg.inv(A)
print(np.dot(A, AInverse).astype(int))
if np.array_equal(np.dot(A,B), np.dot(B,A)):
    print("AB=BA")
else:
    print("AB!=BA")
AdotB=np.dot(A,B)
AT=np.transpose(A)
BT=np.transpose(B)
ABT=np.transpose(AdotB)
BTAT=np.dot(BT,AT)
if np.array_equal(BTAT, ABT):
    print("BTAT=ABT")

[[1 0]
 [0 0]]
AB!=BA
BTAT=ABT


In [23]:
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([[-1],[-3],[9]])
AInv=np.linalg.inv(A)
X=np.matmul(AInv,B)
print("X =",X[0],"Y =",X[1],"Z =")

X = [2.] Y = [1.] Z =


In [24]:
import time
import random
size=1000000
start_time = time.time()
list1=[]
list2=[]
for _ in range(1000000):
  list1.append(random.randint(0,101))
  list2.append(random.randint(0,101))
list3 = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Total Time Taken = ",end_time-start_time,"Seconds")

Total Time Taken =  1.2060682773590088 Seconds

start_time = time.time()
arr1 = np.random.randint(0, 101, size=size)
arr2 = np.random.randint(0, 101, size=size)
result = arr1 + arr2
end_time = time.time()

print("Time taken for element-wise addition (NumPy arrays):", end_time - start_time, "seconds")

SyntaxError: invalid syntax (ipython-input-3627044373.py, line 14)

In [ ]:

size=1000000
start_time = time.time()
list1=[]
list2=[]
for _ in range(1000000):
  list1.append(random.randint(0,101))
  list2.append(random.randint(0,101))
list3 = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("Total Time Taken = ",end_time-start_time,"Seconds")

In [ ]:
start_time = time.time()
arr1 = np.random.randint(0, 101, size=size)
arr2 = np.random.randint(0, 101, size=size)
result = arr1 * arr2
end_time = time.time()

print("Time taken for element-wise addition (NumPy arrays):", end_time - start_time, "seconds")

In [ ]:

size=1000
start_time = time.time()
lists=[]
list1=[]
list2=[]
for _ in range(size):
    list1.append([random.randint(0, 101) for _ in range(size)])
    list2.append([random.randint(0, 101) for _ in range(size)])

list3 = [[sum(list1[i][k] * list2[k][j] for k in range(len(list2))) for j in range(len(list2[0]))]for i in range(len(list1))]


end_time = time.time()
print("Total Time Taken = ",end_time-start_time,"Seconds")


In [ ]:
start_time = time.time()
arr1 = np.random.randint(0, 101, size=size)
arr2 = np.random.randint(0, 101, size=size)
result = np.dot(arr1,arr2)
end_time = time.time()

print("Time taken for element-wise addition (NumPy arrays):", end_time - start_time, "seconds")

In [ ]:
size=1000
start_time = time.time()
list1=[]
list2=[]
for _ in range(size):
    list1.append([random.randint(0, 101) for _ in range(size)])
    list2.append([random.randint(0, 101) for _ in range(size)])
list3 = [[sum(list1[i][k] * list2[k][j] for k in range(len(list2))) for j in range(len(list2[0]))]for i in range(len(list1))]
end_time = time.time()
print("Total Time Taken = ",end_time-start_time,"Seconds")

In [ ]:
start_time = time.time()
arr1 = np.random.randint(0, 101, size=size)
arr2 = np.random.randint(0, 101, size=size)
result = np.matmul(arr1,arr2)
end_time = time.time()

print("Time taken for element-wise addition (NumPy arrays):", end_time - start_time, "seconds")